version: '3'

services:
  pokaplayer:
    restart: unless-stopped
    build: .
    ports:
      - 3000:3000
    links:
      - neteaseapi2
      - mongodb
    depends_on:
      - neteaseapi2
      - mongodb
    volumes:
      - ./config.json:/app/config.json
    
  neteaseapi2:
    build: 
      context: .
      dockerfile: NeteaseAPI2_Dockerfile
    expose:
      - "3000"
      
  mongodb:
    image: mongo:4.0
    command: --smallfiles
    
