version: '3'

services:
  pokaplayer:
    build: .
    ports:
      - "3000"
    links:
      - neteaseapi2
      - mongodb
    depends_on:
      - neteaseapi2
      - mongodb
    
  neteaseapi2:
    build: 
      context: .
      dockerfile: NeteaseAPI2_Dockerfile
    expose:
      - "3000"
      
  mongodb:
    image: mongo:latest
    command: --smallfiles
    
